url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Recode Leadership
email: recodeleadership@gmail.com
description: "We help and guide quiet leaders to lead with confidence so they can be recognized and valued for who they truly are."


# Team names, titles and social links
people:
- name: Amy Mok
  pic: 1
  position: Founder / Leadership and Executive Coach
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/amymok
    - title: substack
      url: https://amymok.substack.com
 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://www.linkedin.com/recodeleadership

# Postal address (add as many lines as necessary)
address:
  - line: X
  - line: X

# Build settings
markdown: kramdown
permalink: pretty